// Shared constants for profile and family member forms (for AI analysis later)

export const RELATIONSHIP_OPTIONS = [
  { value: '', label: 'Select' },
  { value: 'Father', label: 'Father' },
  { value: 'Mother', label: 'Mother' },
  { value: 'Spouse', label: 'Spouse' },
  { value: 'Child', label: 'Child' },
  { value: 'Parent', label: 'Parent' },
  { value: 'Sibling', label: 'Sibling' },
  { value: 'Friend', label: 'Friend' },
  { value: 'Other', label: 'Other' }
]

export const COMMON_AILMENTS = [
  'Hypertension (High Blood Pressure)',
  'Diabetes (Type 1 or 2)',
  'Prediabetes',
  'Asthma',
  'COPD',
  'Arthritis (Osteoarthritis / Rheumatoid)',
  'Heart Disease',
  'Coronary Artery Disease',
  'Heart Failure',
  'High Cholesterol',
  'Hyperlipidemia',
  'Obesity',
  'Anxiety',
  'Depression',
  'Bipolar Disorder',
  'Migraine',
  'Thyroid Disorders (Hypo/Hyper)',
  'Allergies (Environmental/Food)',
  'Sleep Disorders / Insomnia',
  'Sleep Apnea',
  'Chronic Pain',
  'Fibromyalgia',
  'Digestive Issues (IBS / GERD)',
  'Kidney Disease',
  'Liver Disease',
  'Anemia',
  'Osteoporosis',
  'Cancer (any type)',
  'Stroke / TIA',
  'Epilepsy / Seizures',
  'Autoimmune Disease (Lupus, MS, etc.)',
  'Skin Conditions (Eczema, Psoriasis)',
  'Vitamin D / B12 Deficiency',
  'Gout',
  'Chronic Kidney Disease',
  'Atrial Fibrillation',
  'PCOD / PCOS',
  'None / Not applicable'
]

export const COMMON_ALLERGIES = [
  'Milk / Dairy',
  'Gluten / Wheat',
  'Peanuts',
  'Tree Nuts',
  'Eggs',
  'Soy',
  'Fish',
  'Shellfish',
  'Sesame',
  'Sulfites',
  'Penicillin',
  'Other Antibiotics',
  'Latex',
  'Pollen',
  'Dust Mites',
  'Pet Dander',
  'None / No known allergies'
]
